"""Project-local CLI defaults loaded from ``.claude/workflow/defaults.yaml``.

This is the "settings page" for the CLI. The YAML file holds project-level
defaults for the handful of CLI arguments that benefit from per-project
tuning. CLI flags always override these values.

Resolution precedence (lowest → highest):
  1. Built-in production defaults below.
  2. ``.claude/workflow/defaults.yaml`` if present (any subset of keys).
  3. Explicit CLI flag passed by the user.

The loader runs once per CLI invocation after argparse parsing. Arguments
declared with ``default=None`` are eligible for fill-in; arguments with an
explicit non-None default are left alone (the user can still override via
the CLI but the YAML defaults won't reach them).
"""

from __future__ import annotations

import argparse
import logging
import os
import re
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)


_DEFAULTS_RELATIVE_PATH = ".claude/workflow/defaults.yaml"


# Built-in defaults. These are what kodawari uses when neither
# defaults.yaml nor a CLI flag provides a value. Tuned for "production-strict
# multi-LLM pipeline" — see CHANGELOG v0.1 for the empirical basis.
BUILTIN_DEFAULTS: dict[str, Any] = {
    "max_cycles": 5,
    "max_wall_clock_seconds": 3600,
    "real_peer_review": True,
    "rollback_on_failure": True,
    "planner_route": "auto",
    "gate_profile": "advisory",
}


# CLI argparse dest names → defaults.yaml keys. Most are identity; a few CLI
# args use shorter or hyphenated names that argparse normalises differently.
_CLI_DEST_TO_YAML_KEY: dict[str, str] = {
    "max_cycles": "max_cycles",
    "max_wall_clock_seconds": "max_wall_clock_seconds",
    "real_peer_review": "real_peer_review",
    "rollback_on_failure": "rollback_on_failure",
    "planner_route": "planner_route",
    "gate_profile": "gate_profile",
}


def load_workflow_defaults(project_root: Path) -> dict[str, Any]:
    """Read ``.claude/workflow/defaults.yaml`` and return its contents.

    Missing file → empty dict. Parse error → empty dict + WARN log; the
    caller falls back to builtin defaults. We intentionally don't depend on
    PyYAML to keep the runtime dependency surface tiny — the loader uses a
    minimal scalar parser sufficient for the documented schema.
    """
    path = Path(project_root) / _DEFAULTS_RELATIVE_PATH
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    return _parse_minimal_yaml(text, path=path)


def apply_workflow_defaults(args: argparse.Namespace, project_root: Path) -> argparse.Namespace:
    """Fill in ``None`` argparse values from defaults.yaml or builtin defaults.

    Modifies ``args`` in place AND returns it so the caller can chain. Any
    attribute whose current value is None (or missing) is filled from yaml
    defaults first, then builtin defaults. Non-None values (explicit CLI
    flags or argparse defaults) are left unchanged.
    """
    yaml_defaults = load_workflow_defaults(project_root)
    for dest, yaml_key in _CLI_DEST_TO_YAML_KEY.items():
        if not hasattr(args, dest):
            # Only fill defaults for keys the calling command actually declared.
            # Commands without --max-cycles (say, `status`) shouldn't suddenly
            # grow an args.max_cycles attribute.
            continue
        current = getattr(args, dest)
        if current is not None:
            continue
        if yaml_key in yaml_defaults:
            setattr(args, dest, yaml_defaults[yaml_key])
            continue
        if dest in BUILTIN_DEFAULTS:
            setattr(args, dest, BUILTIN_DEFAULTS[dest])
    return args


def render_default_defaults_yaml() -> str:
    """Render the canonical defaults.yaml content used by init-wizard.

    Kept as a single source of truth so the wizard's generated file and the
    builtin runtime defaults can't drift apart. Each line is keyed to a
    constant in BUILTIN_DEFAULTS so updating the builtin also updates the
    documented surface.
    """
    return (
        "# Project-level CLI defaults for kodawari commands.\n"
        "# Generated by `kodawari init-wizard`. Edit values to tune; comment out\n"
        "# any line to revert to the built-in default.\n"
        "#\n"
        "# CLI flags always override these — you can keep this file checked in\n"
        "# and still pass `--max-cycles 10` to one-off override on the command line.\n"
        "\n"
        "# Maximum collaboration cycles per task before giving up.\n"
        f"max_cycles: {BUILTIN_DEFAULTS['max_cycles']}\n"
        "\n"
        "# Whole-loop wall-clock budget in seconds. 0 disables (not recommended in CI).\n"
        f"max_wall_clock_seconds: {BUILTIN_DEFAULTS['max_wall_clock_seconds']}\n"
        "\n"
        "# Run real peer review (mimo / claude / gpt etc., per models.yaml).\n"
        "# Set false to fall back to simulated review only.\n"
        f"real_peer_review: {str(BUILTIN_DEFAULTS['real_peer_review']).lower()}\n"
        "\n"
        "# Roll back implementation when verify fails and retry.\n"
        f"rollback_on_failure: {str(BUILTIN_DEFAULTS['rollback_on_failure']).lower()}\n"
        "\n"
        "# Planning route: 'auto' / 'model' / 'generic'.\n"
        "# 'auto' infers from --task and PRD content (recommended).\n"
        f"planner_route: {BUILTIN_DEFAULTS['planner_route']}\n"
        "\n"
        "# Code-quality gate profile: 'advisory' / 'blocking' / 'strict'.\n"
        f"gate_profile: {BUILTIN_DEFAULTS['gate_profile']}\n"
    )


# ---------------------------------------------------------------------------
# Minimal YAML parser (no PyYAML dependency)
# ---------------------------------------------------------------------------


_SCALAR_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$")
_INT_LITERAL = re.compile(r"^-?\d+$")
_FLOAT_LITERAL = re.compile(r"^-?\d+\.\d+$")


def _parse_minimal_yaml(text: str, *, path: Path) -> dict[str, Any]:
    """Parse the subset of YAML used by defaults.yaml: top-level scalars only.

    Supported value types: int, float, bool (true/false/yes/no/on/off),
    string (quoted or bareword). Anything else logs WARN and returns empty.
    Comments (#) and blank lines are skipped.
    """
    result: dict[str, Any] = {}
    for raw_lineno, raw_line in enumerate(text.splitlines(), 1):
        stripped = raw_line.split("#", 1)[0].rstrip()
        if not stripped.strip():
            continue
        match = _SCALAR_LINE.match(stripped)
        if not match:
            logger.warning("defaults.yaml line %d unparseable: %r (path=%s)", raw_lineno, raw_line, path)
            return {}
        key, raw_value = match.group(1), match.group(2).strip()
        try:
            result[key] = _parse_scalar(raw_value)
        except ValueError as exc:
            logger.warning("defaults.yaml line %d: %s", raw_lineno, exc)
            return {}
    return result


def _parse_scalar(raw: str) -> Any:
    text = raw.strip()
    if not text:
        return ""
    if (text.startswith('"') and text.endswith('"')) or (text.startswith("'") and text.endswith("'")):
        return text[1:-1]
    lowered = text.lower()
    if lowered in {"true", "yes", "on"}:
        return True
    if lowered in {"false", "no", "off"}:
        return False
    if _INT_LITERAL.match(text):
        return int(text)
    if _FLOAT_LITERAL.match(text):
        return float(text)
    return text


__all__ = [
    "BUILTIN_DEFAULTS",
    "apply_workflow_defaults",
    "load_workflow_defaults",
    "render_default_defaults_yaml",
]
