#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


MARKER_BEGIN = "<!-- BEGIN WS-223:DYNAMIC_BASELINE -->"
MARKER_END = "<!-- END WS-223:DYNAMIC_BASELINE -->"


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        text = path.read_text(encoding="utf-8-sig", errors="ignore")
    if text.startswith("\ufeff"):
        text = text.lstrip("\ufeff")
    payload = json.loads(text)
    return payload if isinstance(payload, dict) else None


def _git_head(project_root: Path) -> str:
    try:
        run = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(project_root),
            capture_output=True,
            text=True,
            check=False,
        )
        if run.returncode == 0:
            value = run.stdout.strip()
            if value:
                return value
    except OSError:
        pass
    return "UNKNOWN"


def _count_src_redline_violations(project_root: Path, limit: int = 1000) -> tuple[int, int]:
    src_dir = project_root / "src"
    if not src_dir.exists():
        return 0, 0
    scanned = 0
    violating = 0
    for path in src_dir.rglob("*.py"):
        scanned += 1
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        if len(lines) > limit:
            violating += 1
    return scanned, violating


def _lane_summary(project_root: Path) -> dict[str, Any]:
    planning = project_root / "planning"
    always_payload = _read_json(planning / "lane_stability_always-on.json") or {}
    integration_payload = _read_json(planning / "lane_stability_integration.json") or {}
    return {
        "always_on_status": str(always_payload.get("status") or "MISSING").upper(),
        "integration_status": str(integration_payload.get("status") or "MISSING").upper(),
        "always_on_path": str((planning / "lane_stability_always-on.json").resolve()),
        "integration_path": str((planning / "lane_stability_integration.json").resolve()),
    }


def _gate_summary(project_root: Path) -> dict[str, Any]:
    gate_path = project_root / "planning" / "ci_repo_health_src" / ".gate_result.json"
    payload = _read_json(gate_path) or {}
    return {
        "status": str(payload.get("total_status") or payload.get("status") or "MISSING").upper(),
        "total_violations": int(payload.get("total_violations") or 0),
        "scanned_files": int(payload.get("scanned_files") or 0),
        "path": str(gate_path.resolve()),
    }


def _pytest_summary(project_root: Path, summary_path: Path | None) -> dict[str, Any]:
    payload: dict[str, Any] = {}
    if summary_path is not None and summary_path.exists():
        maybe = _read_json(summary_path) or {}
        payload = maybe if isinstance(maybe, dict) else {}
    return {
        "collected": int(payload.get("collected") or 0),
        "passed": int(payload.get("passed") or 0),
        "skipped": int(payload.get("skipped") or 0),
        "failed": int(payload.get("failed") or 0),
        "source": str(summary_path.resolve()) if summary_path is not None and summary_path.exists() else "UNAVAILABLE",
    }


def build_baseline_snapshot(*, project_root: Path, pytest_summary_path: Path | None, source_commit: str, timestamp: str) -> dict[str, Any]:
    lane = _lane_summary(project_root)
    gate = _gate_summary(project_root)
    pytest_data = _pytest_summary(project_root, pytest_summary_path)
    scanned_src_files, src_redline_violations = _count_src_redline_violations(project_root, limit=1000)
    return {
        "schema_version": "dynamic.baseline.v1",
        "generated_at_utc": timestamp,
        "source_commit": source_commit,
        "project_root": str(project_root),
        "pytest": pytest_data,
        "gate": gate,
        "lane": lane,
        "src_redline": {
            "scanned_files": scanned_src_files,
            "violations_over_1000": src_redline_violations,
            "limit": 1000,
        },
    }


def _render_baseline_markdown(snapshot: dict[str, Any]) -> str:
    pytest_data = dict(snapshot.get("pytest") or {})
    gate = dict(snapshot.get("gate") or {})
    lane = dict(snapshot.get("lane") or {})
    redline = dict(snapshot.get("src_redline") or {})
    lines = [
        MARKER_BEGIN,
        "<!-- auto-generated by scripts/render_dynamic_baseline_docs.py; do not edit manually -->",
        f"- generated_at_utc: `{snapshot.get('generated_at_utc', '')}`",
        f"- source_commit: `{snapshot.get('source_commit', '')}`",
        f"- pytest: `collected={pytest_data.get('collected', 0)}, passed={pytest_data.get('passed', 0)}, skipped={pytest_data.get('skipped', 0)}, failed={pytest_data.get('failed', 0)}`",
        f"- pytest_source: `{pytest_data.get('source', 'UNAVAILABLE')}`",
        f"- strict_gate: `status={gate.get('status', 'MISSING')}, violations={gate.get('total_violations', 0)}, scanned_files={gate.get('scanned_files', 0)}`",
        f"- strict_gate_source: `{gate.get('path', '')}`",
        f"- lane_status: `always-on={lane.get('always_on_status', 'MISSING')}, integration={lane.get('integration_status', 'MISSING')}`",
        f"- lane_sources: `{lane.get('always_on_path', '')}` ; `{lane.get('integration_path', '')}`",
        f"- src_redline: `limit={redline.get('limit', 1000)}, scanned={redline.get('scanned_files', 0)}, violations={redline.get('violations_over_1000', 0)}`",
        MARKER_END,
    ]
    return "\n".join(lines)


def _replace_controlled_block(doc_text: str, rendered_block: str) -> str:
    begin = doc_text.find(MARKER_BEGIN)
    end = doc_text.find(MARKER_END)
    if begin < 0 or end < 0 or end < begin:
        raise ValueError("dynamic baseline markers not found in target document")
    end += len(MARKER_END)
    return doc_text[:begin] + rendered_block + doc_text[end:]


def run(args: argparse.Namespace) -> int:
    project_root = Path(args.project_root).resolve()
    docs = [Path(value).resolve() for value in list(args.doc or [])]
    if not docs:
        docs = [(project_root.parent / "workflowsdk-rebuild.md").resolve()]
    pytest_summary_path = Path(args.pytest_summary_json).resolve() if str(args.pytest_summary_json or "").strip() else None
    source_commit = str(args.source_commit or "").strip() or _git_head(project_root)
    timestamp = str(args.timestamp_utc or "").strip() or _utc_now_iso()

    snapshot = build_baseline_snapshot(
        project_root=project_root,
        pytest_summary_path=pytest_summary_path,
        source_commit=source_commit,
        timestamp=timestamp,
    )
    rendered = _render_baseline_markdown(snapshot)

    for doc_path in docs:
        text = doc_path.read_text(encoding="utf-8")
        updated = _replace_controlled_block(text, rendered)
        doc_path.write_text(updated, encoding="utf-8")

    output_path = Path(args.output_json).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"status": "PASS", "updated_docs": [str(path) for path in docs], "output_json": str(output_path)}, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render controlled dynamic baseline blocks in docs.")
    parser.add_argument("--project-root", default=".", help="Kodawari project root path.")
    parser.add_argument(
        "--doc",
        action="append",
        default=[],
        help="Target markdown document path containing WS-223 baseline markers. Repeatable.",
    )
    parser.add_argument("--pytest-summary-json", default="", help="Optional pytest summary JSON path.")
    parser.add_argument("--output-json", default="planning/dynamic_baseline_snapshot.json", help="Snapshot JSON output path.")
    parser.add_argument("--source-commit", default="", help="Optional source commit SHA override.")
    parser.add_argument("--timestamp-utc", default="", help="Optional UTC timestamp override.")
    return parser


def main() -> int:
    parser = build_parser()
    return run(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
